### ISSUE TITLE
Switching C optimization level from -O3 to -Ofast brings time down to ~5s

### ISSUE THREAD

**Issue by link2xt** [marblestation/benchmark-leapfrog#4]
This way C is highly competitive with Rust

**Comment by link2xt** [comment]
-O3:

    target/optimized/leapfrog  124.53s user 0.00s system 100% cpu 2:04.53 total

-Ofast

    target/optimized/leapfrog  5.12s user 0.00s system 100% cpu 5.120 total

**Comment by marblestation** [comment]
With the current version of the code on my machine:

C with -O3: 2m24.406s
C with -Ofast: 2m6.124s
Fortran: 2m47.544s
Rust: 2m7.585s
Go: 5m15.997s

So, you are right, -Ofast brings times close to Rust times. But I would prefer not to use that optimization flag since " It also enables optimizations that are not valid for all standard-compliant programs." as described in the [gcc](https://gcc.gnu.org/onlinedocs/gcc/Optimize-Options.html) page.
