### ISSUE TITLE
Rust isn't actually doing any work?

### ISSUE THREAD

**Issue by ChrisJefferson** [marblestation/benchmark-leapfrog#6]
I'm not an expert on rust, but I added to the end: `println!("{:?}",x);` (to check the answer), to the end of `main` and now the runtime on my machine has gone from 11 seconds to more than 2 minutes. Still running.

**Comment by ChrisJefferson** [comment]
Update: final output is 134 seconds, and also the output is `[[NaN, NaN, NaN], [NaN, NaN, NaN]]` (batman)

**Comment by Omegaice** [comment]
I modified all the tests to randomize the values of X, V, A and M and then at the end of the code printed out the first value of each. I get the following times:

Go: 288.13s
C: 169.73s
Fortran: 145.25s
Rust: 139.03s

Obviously this was a very quick modification and I am now adding some noise because the timing includes the initialization of the arrays rather than a memset. 

To do this properly I would want the code to read in its initial data from the disk, calculate the time it takes to do the integration steps and then write out the results to a file.

**Comment by StefanKarpinski** [comment]
PR fixing this: https://github.com/marblestation/benchmark-leapfrog/pull/8

**Comment by marblestation** [comment]
Now all the codes print the final positions: https://github.com/marblestation/benchmark-leapfrog/commit/8b89e8d70138e8518d0c8b1444511acd27959fdc, https://github.com/marblestation/benchmark-leapfrog/commit/33c6945731cde225a324a8b82a9996496706879e

On my machine:

C: 2m24.406s
Fortran: 2m47.544s
Rust: 2m7.585s
Go: 5m15.997s

There is still NaN since everything is initialised to zero and there is a division by zero. That's something to improve, not sure how it affects the execution time comparison.
